/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wpnshiyspzpnnfmomegm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbnNoaXlzcHpwbm5mbW9tZWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzg1NDQsImV4cCI6MjA3MTc1NDU0NH0.vtxIUdSrTx-wyz8ysEcXmxkDecS7BIBNL2Vq7YV-FwY"